/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BlockResize: typeof import('./components/BlockResize/index.vue')['default']
    ColorPicker: typeof import('./components/ColorPicker/index.vue')['default']
    copy: typeof import('./components/BlockResize/index copy.vue')['default']
    Drager: typeof import('./components/Drager/drager.vue')['default']
    DragResizeRotate: typeof import('./components/DragResizeRotate/index.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    Header: typeof import('./components/Header/editorHeader.vue')['default']
    Image: typeof import('./components/image/index.vue')['default']
    'Index copy': typeof import('./components/BlockResize/index copy.vue')['default']
    IndexBefore: typeof import('./components/DragResizeRotate/index-before.vue')['default']
    IndexVue3: typeof import('./components/DragResizeRotate/index-vue3.vue')['default']
    Rotate: typeof import('./components/Drager/rotate.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Show: typeof import('./components/show/index.vue')['default']
    Tooltip: typeof import('./components/Tooltip/index.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
